Name middleware
cdimascio/express-openapi-validator pull request #583
Opened 2021-04-14 20:04 UTC by benblack86

For tracing, anonymous functions wouldn't show up with name. I've converted these anonymous functions to named functions so it is a little more clearer what is happening. Let me know if you think a different naming schema would be better.

![Screen Shot 2021-04-14 at 16 01 18](https://user-images.githubusercontent.com/315836/114771631-cb55e480-9d3a-11eb-80a4-639eb5d9f8e9.png)

2021-04-20 01:27 UTC, cdimascio requested changes

2021-04-20 01:27 UTC, cdimascio commented on src/openapi.validator.ts
> +    middlewares.push(function OpenApiValidatorPathParamsMiddleware(req, res, next) {
nit: remove the `OpenApiValidator` prefix from each named middleware function

2021-04-20 01:27 UTC, cdimascio commented on src/openapi.validator.ts
> +    const that = this; // using named functions instead of anonymous functions to allow traces to be more useful
rename `that` to `self`

2021-04-20 01:27 UTC, cdimascio commented
@benblack86 thanks!

2021-04-20 12:42 UTC, benblack86 commented
Updated

2021-04-22 01:23 UTC, cdimascio commented on src/openapi.validator.ts
> +    middlewares.push(function PathParamsMiddleware(req, res, next) {
one more nit. use lower case `camelCase` for the function names e.g. `pathParamsMiddleware`. apologies for not being clear with my first comment

2021-04-22 02:34 UTC, benblack86 commented
Updated

2021-04-23 01:02 UTC, cdimascio approved these changes
thanks!

2021-04-23 01:02 UTC, merged