feat(path-to-regexp): path-to-regexp 8.1.0 update
cdimascio/express-openapi-validator pull request #976
Opened 2024-09-12 14:53 UTC by frankkeefer

* Change path-to-regexp 6.2.2 to 8.1.0
* Update code to handled changes in path-to-regexp v6.x.x -> v8.x.x

2024-09-12 16:03 UTC, cvchauhan commented on src/middlewares/openapi.metadata.ts
> +      const regexpObj = pathToRegexp(expressRoute, pathOpts);
we can remove let keys = [];
and directly use 
 const { regexpObj, keys } = pathToRegexp(expressRoute, pathOpts);

2024-09-12 16:04 UTC, cvchauhan requested changes
we can remove let keys = []; and keys = regexpObj.keys;
and directly use
const { regexpObj, keys } = pathToRegexp(expressRoute, pathOpts);

2024-09-12 18:31 UTC, frankkeefer commented on src/middlewares/openapi.metadata.ts
> +      const regexpObj = pathToRegexp(expressRoute, pathOpts);
Added in requested changes. 
* removed let keys =[] and related uses
* removed const regexp = regepObj.regexp; and related uses
All current unit tests still pass locally

2024-09-12 18:33 UTC, cvchauhan approved these changes

2024-09-13 23:28 UTC, cdimascio approved these changes
thank you. this is great

2024-09-14 19:49 UTC, merged

2024-09-16 08:07 UTC, dogmatic69 commented
Please create a release 🙏🏻